import Head from 'next/head'

import { signIn, signOut, useSession } from 'next-auth/client'


export default function Home() {
  const [session, loadingsession] = useSession();

  if(loadingsession){
    return <p>
      Loading ...
    </p>;
  }

  console.log('id = '+process.env.GOOGLE_ID)
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session && (
        <div>
          <button onClick = {()=>signIn()}>
            Sign In
          </button>
        </div>
      )}
      {session && (
        <>
          <h4>You are logged in Your details are</h4>
          <div >
            <h4>Email:{session.user.email}</h4>
            <br/>

            {session.user.image&& (
              <span>
                <img src={session.user.image} alt={session.user.name} />
              </span>
            )}
          </div>
          <br/>
          <br/>
          <br/>
          <button onClick = {()=>signOut()}>
            Sign out
          </button>
        </>
      )}
      

      
    </div>
  )
}
